# MULTI-OBJECTIVE OPTIMIZATION BY RATIO ANALYSIS (MOORA)


Metode ini memiliki tingkat selektifitas yang baik karena dapat menentukan tujuan dari kriteria yang bertentangan. Dimana kriteria dapat bernilai menguntungkan (benefit) atau yang tidak menguntungkan (cost). (Rokhman, Rozi, and Asmara 2017). Metode ini yang diperkenalkan oleh Brauers dan Zavadkas (2006) pertama kali digunakanoleh Brauers dalam suatu pengambilan dengan multi-criteria decision making (MCDM). Metode MOORA memiliki tingkat fleksibilitas dan kemudahan untuk dipahami dalam memisahkan bagian subjektif dari suatu proses evaluasi kedalam kriteria bobot keputusan dengan beberapa atribut pengambilan keputusan

## Langkah-langkah Metode MOORA

1. Mengidentifikasi atribut atau kriteria. Tentukan apakah atribut/kriteria termasuk __*benefit*__ atau __*cost*__.
2. Membuat matrix keputusan (__*decision matrix*__).
3. Membuat matrix ternomalisasi.
4. Menghitung nilai optimasi multi-obyektif.
5. Menentukan ranking alternatif.

---
Untuk mempermudah pemahaman kita tentang metode MOORA, kita akan menggunakan studi kasus dan penerapan kode python secara langsung.

---



## Studi Kasus

SMA XYZ akan melakukan seleksi untuk menentukan Guru terbaik tahun ajaran 2019/2020. Beberapa kriteria yang akan digunakan dalam penilaian selesi tersebut adalah, 

1. Memilki pretasi dalam bidang akademik maupun non-akademik. (C1)
2. Memiliki sifat kepemimpinan baik. (C2)
3. Tingkat kesibukan. (C3)
4. Absensi. (C4)
5. Mempunyai keahlian dalam bidang ekstrakulikuler. (C5)
6. Memiliki hubungan sejawat baik. (C6)

Sedangkan kandidat guru terbaik adalah sebagai berikut,

1. Hamdi, S.Pd.
2. Purwanto, S.Pd.
3. Lutfi Subhan, S.Pd.
4. Dewi Rosatika, S.Pd.
5. Tati Sunarti, S.Pd.

Pihak panitia seleksi, menentukan bobot untuk setiap kriteria adalah sebagai berikut,

|No | Kriteria | Bobot |
|:---:|:---:|:---:|
| 1 | C1 | 0.290 |
| 2 | C2 | 0.173 |
| 3 | C3 | 0.091 |
| 4 | C4 | 0.162 |
| 5 | C5 | 0.080 |
| 6 | C6 | 0.204 |

Penilaian tiap kriteria, ditentukan oleh skala berikut,

Untuk C1, C2, dan C5

| Opsi Penilaian | Skala Nilai |
|:---:|:---|
| Ya | 1 |
| Tidak | 0 |

Untuk C3

| Opsi Penilaian | Skala Nilai |
|:---:|:---:|
| Sangat Sibuk | 1 |
| Sibuk | 2 |
| Wajar | 3 |
| Tidak Sibuk | 4 |

Untuk C4

| Opsi Penilaian | Skala Nilai |
|:---:|:---:|
| Sangat Rajin | 4 |
| Rajin | 3 |
| Kurang Rajin | 2 |
| Tidak Rajin | 1 |

Untuk C6

| Opsi Penilaian | Skala Nilai |
|:---:|:---:|
| Sangat Baik | 4 |
| Baik | 3 |
| Kurang Baik | 2 |
| Tidak Baik | 1 |

---
### Langkah 1 : Identifikasi Atribut

Berdasarkan kriteria yang digunakan, maka dapat disimpulkan bahwa C1,C2,C5, dan C6 memiliki atribut __*benefit*__. Sedangkan C3 dan C4 memiliki atribut __*cost*__.

In [12]:
# Membuat Label untuk benefit dan cost
# Benefit = 1
# Cost = 0
# Label untuk C1, C2, C3, C4, C5, C6 secara berutan

label = [1, 1, 0, 0, 1, 1]

---
### Langkah 2 : Membuat Decision Matrix

Pada studi kasus kali ini, didapatkan decision matrix sebagai berikut,

| *** | C1 | C2 | C3 | C4 | C5 | C6 |
|---|---|---|---|---|---|---|
| A1 | 1 | 1 | 3 | 4 | 1 | 4 |
| A2 | 1 | 1 | 4 | 3 | 1 | 3 |
| A3 | 1 | 1 | 4 | 4 | 1 | 4 |
| A4 | 1 | 1 | 3 | 3 | 0 | 3 |
| A5 | 1 | 1 | 3 | 3 | 1 | 4 |

In [3]:
# Implementasi Matrix Pada Python
# Kita akan menggunakan bantuan Numpy untuk membuat 2d array

import numpy as np

init_matrix = np.array([[1,1,3,4,1,4], [1,1,4,3,1,3], [1,1,4,4,1,4], [1,1,3,3,0,3], [1,1,3,3,1,4]])

print(init_matrix) #cek hasil matrix

[[1 1 3 4 1 4]
 [1 1 4 3 1 3]
 [1 1 4 4 1 4]
 [1 1 3 3 0 3]
 [1 1 3 3 1 4]]


---
### Langkah 3 : Membuat Matrix Ternormaliasi

Selanjutnya, kita harus melakukan normalisasi terhadap semua nilai pada decision matrix. Menurut Braures, normalisasi terbaik pada metode MOORA adalah menggunakan persamaan barikut,

\begin{equation}
x_{ij}^* = \frac{x_{ij}}{\sqrt{[\sum_{1}^{m}x_{ij}^2]}}
\end{equation}

Dimana,

$r_{ij}$ adalah nilai hasil normalisasi pada __kriteria__ ke-$i$ __alternatif__ ke-$j$

$x_{ij}$ adalah nilai asli matrix pada __kriteria__ ke-$i$ __alternatif__ ke-$j$

$m$ adalah banyaknya alternatif

---
#### Implemantasi Python

__Transpose Matrix (Opsional)__

Decision matrix yang kita buat memiliki format (alternatif x kriteria). Namun, persamaan yang kita gunakan melakukan penjumlahan nilai satu kriteria untuk semua alternatif. Jika disimulasikan, maka looping akan berjalan setiap kolom terlebih dahulu kemudian dilanjutkan dengan baris. Padahal, format numpy 2d array adalah (baris x kolom). Untuk mempermudah algoritma normalisasi, maka cara termudah adalah melakukan operasi transpose pada decision matrix yang kita miliki saat ini. Sehingga bentuk matrix yang akan digunakan dalam python adalah sebagai berikut,

__Decision Matrix__

| *** | C1 | C2 | C3 | C4 | C5 | C6 |
|---|---|---|---|---|---|---|
| A1 | 1 | 1 | 3 | 4 | 1 | 4 |
| A2 | 1 | 1 | 4 | 3 | 1 | 3 |
| A3 | 1 | 1 | 4 | 4 | 1 | 4 |
| A4 | 1 | 1 | 3 | 3 | 0 | 3 |
| A5 | 1 | 1 | 3 | 3 | 1 | 4 |


__Decision Matrix Transpose__

| *** | A1 | A2 | A3 | A4 | A5 |
|---|---|---|---|---|---|
| C1 | 1 | 1 | 1 | 1 | 1 |
| C2 | 1 | 1 | 1 | 1 | 1 |
| C3 | 3 | 4 | 4 | 3 | 3 |
| C4 | 4 | 3 | 4 | 3 | 3 |
| C5 | 1 | 1 | 1 | 0 | 1 |
| C6 | 4 | 3 | 4 | 3 | 4 |

In [10]:
# Pada modul ini akan diterapkan normalisasi matrix sesuai dengan persamaan
# Kita akan membuat fungsi yang akan menerima paramater berupa array 2d
import math

def normalization(matrix):
    # Transpose Decision Matrix
    matrix = matrix.transpose()
    row_values = []
    norm_matrix = []
    
    for i in range(matrix.shape[0]): # Looping per baris (kriteria)
        # Menghitung sum tiap x_{ij}^2
        sum_row = sum([pow(x,2) for x in matrix[i]])
        
        for j in range(matrix[i].shape[0]): # Looping per kolom (alternatif)
            # membangi nilai asli x_{ij} dengan hasil akar
            r_value = matrix[i][j] / math.sqrt(sum_row)
            
            # Masukkan hasil normalisasi ke list tiap baris
            row_values.append(r_value)
        
        #Masukkan hasil normalisasi per baris ke matrix normalisasi
        norm_matrix.append(row_values)
        
        #Kosongkan list normalisasi perbaris
        row_values = []
            
    # Ubah dalam bentuk numpy array
    norm_matrix = np.asarray(norm_matrix)
    
    # Return dalam bentuk transporse agar kembali ke format awal
    return norm_matrix.transpose()

In [11]:
# Test fungsi normalisasi
n_matrix = normalization(init_matrix)

# Cetak hasil normalisasi
print(n_matrix)

[[0.4472136  0.4472136  0.39056673 0.52075564 0.5        0.49236596]
 [0.4472136  0.4472136  0.52075564 0.39056673 0.5        0.36927447]
 [0.4472136  0.4472136  0.52075564 0.52075564 0.5        0.49236596]
 [0.4472136  0.4472136  0.39056673 0.39056673 0.         0.36927447]
 [0.4472136  0.4472136  0.39056673 0.39056673 0.5        0.49236596]]


---
### Langkah 4 : Menghitung Nilai Optimasi Multi-Obyektif

Pada metode MOORA terdapat 2 jenis perhitungan nilai optimasi multi-obyektif, yaitu jika kriteria tidak terbobot dan kriteria terbobot. Kriteria tidak terbobot adalah jika setiap kriteria memiliki nilai kepentingan yang sama, sehingga tidak memiliki bobot. Sedangkan terbobot jika masing-masing kriteria memiliki tingkat kepentingan yang berbeda dalam hal menentukan keputusan.

#### Kriteria Tidak Terbobot

Pada kondisi kriteria tidak terbobot, maka persamaan yang digunakan adalah,

\begin{equation}
y_{i}^*= \sum_{i=1}^{i=g}x_{ij}^* - \sum_{i=g+1}^{i=n}x_{ij}^*
\end{equation}

Dimana,

$i = 1,2,3, . . .,g$ dimana $g$ adalah kriteria dengan atribut __*benefit*__ atau status maximazed.

$i=g+1, g+2, . . ., n$ dimana $n$ adalah kriteria dengan atribut __*cost*__ atau status minimized.

$x_{ij}^*$ adalah nilai ternormalisasi pada alternatif ke-$i$ kriteria ke-$j$.

$y_{i}^*$ adalah nilai optimasi untuk alternatif ke-$i$.

#### Kriteria Terbobot

Pada kriteria terbobot, tiap nilai ternormalisasi harus dikalikan dengan bobot masing-masing kriteria. Sehingga persamaan yang digunakan berubah menjadi,


\begin{equation}
y_{i}^*= \sum_{i=1}^{i=g}x_{ij}^* * w_{j} - \sum_{i=g+1}^{i=n}x_{ij}^* * w_{j}
\end{equation}

Dimana,

$i = 1,2,3, . . .,g$ dimana $g$ adalah kriteria dengan atribut __*benefit*__ atau status maximazed.

$i=g+1, g+2, . . ., n$ dimana $n$ adalah kriteria dengan atribut __*cost*__ atau status minimized.

$x_{ij}^*$ adalah nilai ternormalisasi pada alternatif ke-$i$ kriteria ke-$j$.

$w_{j}$ adalah bobot untuk setiap kriteria.

$y_{i}^*$ adalah nilai optimasi untuk alternatif ke-$i$.

---
Pada studi kasus yang kita kerjakan, kebetulan setiap kriteria memiliki bobot, sehingga kita harus membuat matrix normaliasis terbobot terlebih dahulu

In [21]:
# Kalkulasi skor normalisasi terbobot

# Bobot untuk Kriteria C1, C2, C3, C4, C5, dan C6
c_weights = np.array([0.290, 0.173, 0.091, 0.162, 0.080, 0.204])

# Fungsi untuk kalkulasi matrix terbobot. Paramter yang diperlukan adalah nilai ternormalisasi dan bobot
# Untuk mempermudah perhitungan, lakukan operasi transpose pada matrix ternormalisasi.
# Ingat! Kriteria adalah baris, alternatif adalah kolom setelah proses transpose
def weighted_normalization(n_matrix, c_weights):
    # Buat salinan nilai ternormalisasi dan transpose
    norm_weighted = n_matrix.transpose()
    
    for i in range(c_weights.shape[0]): # Looping tiap kriteria
        # Kalkulasi normalisasi terbobot
        norm_weighted[i] = [r * c_weights[i] for r in norm_weighted[i]]
    
    # Ubah ke bentuk numpy array
    norm_weighted = np.asarray(norm_weighted)
    
    # Return ke dalam format matrix semula
    return norm_weighted.transpose()

In [22]:
# Test fungsi pembobotan
w_matrix = weighted_normalization(n_matrix, c_weights)

# Cetak hasil
print(w_matrix)

[[0.12969194 0.07736795 0.03554157 0.08436241 0.04       0.10044266]
 [0.12969194 0.07736795 0.04738876 0.06327181 0.04       0.07533199]
 [0.12969194 0.07736795 0.04738876 0.08436241 0.04       0.10044266]
 [0.12969194 0.07736795 0.03554157 0.06327181 0.         0.07533199]
 [0.12969194 0.07736795 0.03554157 0.06327181 0.04       0.10044266]]


In [29]:
# Implementasi Menghitung Nilai 
def optimize_value(w_matrix, label):
    y_values = []
    
    for i in range(w_matrix.shape[0]):
        max_val = []
        min_val = []
        
        for j in range(w_matrix[i].shape[0]):
            # Hitung benefit
            if label[j] == 1:
                max_val.append(w_matrix[i][j])
            # Hitung cost
            else:
                min_val.append(w_matrix[i][j])
        
        y = sum(max_val) - sum(min_val)
        y_values.append(y)
    
    return np.asarray(y_values)

In [30]:
# Test fungsi nilai optimasi
result = optimize_value(w_matrix, label)

print(result)

[0.22759856 0.21173131 0.21575137 0.1835785  0.24868917]


---
# Wrap Up The Codes
---

In [31]:
# Import Libary
import numpy as np
import math

In [32]:
# Data Studi Kasus
label = [1, 1, 0, 0, 1, 1]
init_matrix = np.array([[1,1,3,4,1,4], [1,1,4,3,1,3], [1,1,4,4,1,4], [1,1,3,3,0,3], [1,1,3,3,1,4]])
c_weights = np.array([0.290, 0.173, 0.091, 0.162, 0.080, 0.204])

In [34]:
'''
Fungsi-fungsi perhitungan MOORA
'''


# Kita akan membuat fungsi yang akan menerima paramater berupa array 2d

def normalization(matrix):
    # Transpose Decision Matrix
    matrix = matrix.transpose()
    row_values = []
    norm_matrix = []
    
    for i in range(matrix.shape[0]): # Looping per baris (kriteria)
        # Menghitung sum tiap x_{ij}^2
        sum_row = sum([pow(x,2) for x in matrix[i]])
        
        for j in range(matrix[i].shape[0]): # Looping per kolom (alternatif)
            # membangi nilai asli x_{ij} dengan hasil akar
            r_value = matrix[i][j] / math.sqrt(sum_row)
            
            # Masukkan hasil normalisasi ke list tiap baris
            row_values.append(r_value)
        
        #Masukkan hasil normalisasi per baris ke matrix normalisasi
        norm_matrix.append(row_values)
        
        #Kosongkan list normalisasi perbaris
        row_values = []
            
    # Ubah dalam bentuk numpy array
    norm_matrix = np.asarray(norm_matrix)
    
    # Return dalam bentuk transporse agar kembali ke format awal
    return norm_matrix.transpose()


# Fungsi untuk kalkulasi matrix terbobot. Paramter yang diperlukan adalah nilai ternormalisasi dan bobot
# Untuk mempermudah perhitungan, lakukan operasi transpose pada matrix ternormalisasi.
# Ingat! Kriteria adalah baris, alternatif adalah kolom setelah proses transpose
def weighted_normalization(n_matrix, c_weights):
    # Buat salinan nilai ternormalisasi dan transpose
    norm_weighted = n_matrix.transpose()
    
    for i in range(c_weights.shape[0]): # Looping tiap kriteria
        # Kalkulasi normalisasi terbobot
        norm_weighted[i] = [r * c_weights[i] for r in norm_weighted[i]]
    
    # Ubah ke bentuk numpy array
    norm_weighted = np.asarray(norm_weighted)
    
    # Return ke dalam format matrix semula
    return norm_weighted.transpose()


# Implementasi Menghitung Nilai Optimasi
def optimize_value(w_matrix, label):
    y_values = []
    
    for i in range(w_matrix.shape[0]):
        max_val = []
        min_val = []
        
        for j in range(w_matrix[i].shape[0]):
            # Hitung benefit
            if label[j] == 1:
                max_val.append(w_matrix[i][j])
            # Hitung cost
            else:
                min_val.append(w_matrix[i][j])
        
        y = sum(max_val) - sum(min_val)
        y_values.append(y)
    
    return np.asarray(y_values)

### Bagaimana Cara Mengurutkan Rankingnya ?
---

Silahkan dicoba sendiri :)