## Technique for Order Performance by Similarity to Ideal Solution (TOPSIS)

Metode TOPSIS diperkenalkan pertama kali oleh Yoon dan Hwang dan mampu memberikan penilaian yang spesifik terhadap setiap alternatif yang dinilai. Metode TOPSIS menggunakan prinsip bahwa alternatif yang terpilih harus mempunyai jarak terdekat dari solusi ideal positif dan jarak terpanjang (terjauh) dari solusi ideal negatif dari sudut pandang geometris dengan menggunakan jarak Euclidean (jarak antara dua titik) untuk menentukan kedekatan relatif dari suatu alternatif dengan solusi optimal (Sriani dan Raissa Amanda Putri, 2018). Metode TOPSIS merupakan salah satu contoh dari Multi-Attribute Decision Making (MADM).

## Contoh Kasus
Untuk memilih kucing yang akan menjadi pemenang dalam Kontes Kucing Maine Coon, dibuat sebuah Sistem Pendukung Keputusan dengan Metode TOPSIS. Kriteria yang digunakan, adalah, 

1. Ukuran tubuh (C1)
2. Penampilan (C2)
3. Profil kucing (C3)
4. Adanya fitur tubuh yang buruk (C4)

Kucing yang dinilai adalah Kucing 1, Kucing 2 , Kucing 3, dan Kucing 4.

Skala pembobotan tiap kriteria dan bobot kriteria adalah sebagai berikut

__Skala Nilai untuk C1, C2, dan C3__

| Skala | Nilai |
| :------| ----- |
| Sangat Kurang | 1 |
| Kurang | 2 |
| Baik | 3 |
| Sangat Baik | 4 |

__Skala Nilai untuk C4__

| Skala | Nilai |
| :--- | --- |
| Ada | 4 |
| Tidak Ada | 1 |

__Bobot Tiap Criteria__

| Kriteria | Bobot |
| :--- | --- |
| C1 | 20 |
| C2 | 30 |
| C3 | 30 |
| C4 | 20 |

### Penilaian Kucing Berdasarkan Kriteria
Berikut merupakan hasil penjurian kucing berdasarkan kriteria yang telah ditetapkan

|*** | Kucing 1 | Kucing 2 | Kucing 3 | Kucing 4 |
|---|---|---|---|---|
| C1 | Baik | Baik | Sangat Baik | Baik |
| C2 | Sangat Baik | Kurang | Sangat Baik | Sangat Baik |
| C3 | Kurang | Sangat Baik | Baik | Baik |
| C4 | Tidak Ada | Tidak Ada | Ada | Tidak Ada |

---
## Tahap-tahap Penyelesaian dengan TOPSIS
---

### 1. Ubah Matrix Penilaian Sesuai dengan Skala
|*** | Kucing 1 | Kucing 2 | Kucing 3 | Kucing 4 |
|---|---|---|---|---|
| C1 | 3 | 3 | 4 | 3 |
| C2 | 4 | 2 | 4 | 4 |
| C3 | 2 | 4 | 3 | 3 |
| C4 | 1 | 1 | 4 | 1 |

Pada kode python, kita dapat memanfaatkan array 2d.Pada kasus ini, kita akan membuat __Kriteria__ sebagai __baris__, __alternatif__ sebagai __kolom__. Pada modul ini, array 2d akan dibuat dengan memanfaatkan __numpy__ array.

In [3]:
# Import Library Numpy dan disimapan dalam nama 'np'
import numpy as np

# Membuat array 2d sesuai dengan matrix penyekalaan
init_matrix = np.array([[3,3,4,3], [4,2,4,4], [2,4,3,3], [1,1,4,1]])
# Cek hasil array 2d
print(init_matrix)

[[3 3 4 3]
 [4 2 4 4]
 [2 4 3 3]
 [1 1 4 1]]


### 2. Normalisasi Matrix

Normalisasi Matrix dilakukan dengan menggunakan persamaan, 

\begin{equation}
r_{ij} = \frac{x_{ij}}{\sqrt{\sum_{1}^{m}x_{ij}^2}}
\end{equation}

Dimana,

$r_{ij}$ adalah nilai hasil normalisasi pada alternatif ke-$i$ kriteria ke-$j$

$x_{ij}$ adalah nilai asli matrix pada alternatif ke-$i$ kriteria ke-$j$

$m$ adalah banyaknya alternatif

In [13]:
# Pada modul ini akan diterapkan normalisasi matrix sesuai dengan persamaan
# Kita akan membuat fungsi yang akan menerima paramater berupa array 2d
import math

def normalization(matrix):
    row_values = []
    norm_matrix = []
    
    for i in range(matrix.shape[0]): # Looping per baris (kriteria)
        # Menghitung sum tiap x_{ij}^2
        sum_row = sum([pow(x,2) for x in matrix[i]])
        
        for j in range(matrix[i].shape[0]): # Looping per kolom (alternatif)
            # membangi nilai asli x_{ij} dengan hasil akar
            r_value = matrix[i][j] / math.sqrt(sum_row)
            
            # Masukkan hasil normalisasi ke list tiap baris
            row_values.append(r_value)
        
        #Masukkan hasil normalisasi per baris ke matrix normalisasi
        norm_matrix.append(row_values)
        
        #Kosongkan list normalisasi perbaris
        row_values = []
            
    # Rturn matrix normalisasi dalam bentuk numpy array
    return np.asarray(norm_matrix)

In [14]:
# Testing Fungsi Normalisasi
norm = normalization(init_matrix)
print(norm)

[[0.45749571 0.45749571 0.60999428 0.45749571]
 [0.5547002  0.2773501  0.5547002  0.5547002 ]
 [0.32444284 0.64888568 0.48666426 0.48666426]
 [0.22941573 0.22941573 0.91766294 0.22941573]]


### 2. Mehingtung Skor Terbobot

Untuk menghitung skor terbobot, kita harus mengkalikan antara setiap nilai $r_{ij}$ dengan bobot tiap kriteria. Persamaan yang digunakan adalah,

\begin{equation*}
y_{ij} = \frac{r_{ij}}{w_j}
\end{equation*}

Dimana,

$y_{ij}$ merupakan nilai terbobot untuk alternatif ke-$i$ kriteria ke-$j$

$r_{ij}$ merupakan nilai normalisasi untuk alternatif ke-$i$ kriteria ke-$j$

$w_{j}$ merupakan bobot untuk kriteria ke-$j$

In [19]:
# Kalkulasi skor normalisasi terbobot

# Bobot untuk Kriteria C1, C2, C3, dan C4
c_weights = np.array([20,30,30,20])

# Fungsi untuk kalkulasi matrix terbobot. Paramter yang diperlukan adalah nilai ternormalisasi dan bobot
# Ingat! Kriteria adalah baris, Kolom adalah alternatif
def weighted_normalization(n_matrix, c_weights):
    # Buat salinan nilai ternormalisasi
    norm_weighted = n_matrix
    
    for i in range(c_weights.shape[0]): # Looping tiap kriteria
        # Kalkulasi normalisasi terbobot
        norm_weighted[i] = [r * c_weights[i] for r in norm_weighted[i]]
    
    return np.asarray(norm_weighted)

In [21]:
# Testing Matrix Normalisasi terbobot
w_norm = weighted_normalization(norm, c_weights)
print(w_norm)

[[ 9.14991422  9.14991422 12.19988563  9.14991422]
 [16.64100589  8.32050294 16.64100589 16.64100589]
 [ 9.73328527 19.46657054 14.5999279  14.5999279 ]
 [ 4.58831468  4.58831468 18.35325871  4.58831468]]


### 3. Menentukan Solusi Ideal

Langkah selanjutnya adalah menentukan solusi ideal positif dan negatif. Namun sebelumnya, kita harus melakukan analisis terhadap kriteria yang kita gunakan. Kelompokkan kriteria ke dalam _**benefit**_ dan _**cost**_. Dari studi kasus yang kita miliki, dapat disimpulkan bahawa,

Kriteria C1, C2, dan C3 adalah _**benefit**_
Kriteria C4 adalah _**cost**_

---
#### 3.1 Solusi Ideal Positif
Pada solusi ideal positif atau $A^+$, maka digunakan persamaan,

\begin{equation*}
A^+ = {(max (y_{ij}) | j \epsilon J), (min (y_{ij}) | j \epsilon J^/) | i = 1,2,3, ..., m}
\end{equation*}

Dimana,

$J$ adalah himpunan kriteria benefit dan $J^/$ adalah himpunan kriteria cost

#### 3.2 Solusi Ideal Negatif
Pada solusi ideal positif atau $A^-$, maka digunakan persamaan,

\begin{equation*}
A^- = {(min (y_{ij}) | j \epsilon J), (max (y_{ij}) | j \epsilon J^/) | i = 1,2,3, ..., m}
\end{equation*}

Dimana,

$J$ adalah himpunan kriteria benefit dan $J^/$ adalah himpunan kriteria cost

In [22]:
# Membuat label benefit dan cost untuk tiap kriteria
# Benefit = 1
# Cost = 0
c_label = np.array([1, 1, 1, 0])

In [31]:
# Fungsi mencari solusi ideal positif dan negatif
# Parameter yang dibutuhkan adalah, matrix normalisasi terbobot dan label benefit cost untuk tiap kriteria

def ideal(w_norm, c_label):
    a_positif = []
    a_negatif = []
    
    for i in range(w_norm.shape[0]):
        if c_label[i] == 1:
            # Untuk ideal positif
            a_max = max(w_norm[i])
            a_positif.append(a_max)
            
            # Untuk ideal negatif
            a_min = min(w_norm[i])
            a_negatif.append(a_min)
        elif c_label[i] == 0:
            # Untuk ideal positif
            a_max = min(w_norm[i])
            a_positif.append(a_max)
            
            # Untuk ideal negatif
            a_min = max(w_norm[i])
            a_negatif.append(a_min)
    
    ideal_value = np.array([a_positif, a_negatif])
    
    # Return dalam bentuk transpose sehingga baris = kriteria, kolom = solusi ideal positif dan negatid
    return ideal_value.transpose()

In [32]:
# Testing Solusi Ideal
ideal_v = ideal(w_norm, c_label)
print(ideal_v)

[[12.19988563  9.14991422]
 [16.64100589  8.32050294]
 [19.46657054  9.73328527]
 [ 4.58831468 18.35325871]]


### 4. Menentukan Jarak Alternatif dengan Solusi Ideal
#### 4.1 Jarak Alternatif dengan Solusi Ideal Positif

Untuk menghitung jarak alternatif dengan solusi ideal positif dapat digunakan persamaan Eucledean Distance,

\begin{equation}
D^+_{i} = \sqrt{\sum_{j=1}^{n}(A^+_{j}-y_{ij})^2}
\end{equation}
\begin{equation}
i = 1,2,3, ... m
\end{equation}

Dimana, 

$D^+_{i}$ adalah jarak alternatif dengan solusi ideal positif

$A^+_{j}$ adalah nilai solusi ideal positif kriteria ke-$j$

$y_{ij}$ adalah nilai matrix normalisasi terbobot pada alternatif ke-$i$ kriteria ke-$j$

$m$ adalah jumlah alternatif dan $n$ adalah jumlah kriteria

#### 4.2 Jarak Alternatif dengan Solusi Ideal Negatif
Untuk menghitung jarak alternatif dengan solusi ideal positif dapat digunakan persamaan Eucledean Distance,

\begin{equation}
D^-_{i} = \sqrt{\sum_{j=1}^{n}(y_{ij}-A^-_{j})^2}
\end{equation}
\begin{equation}
i = 1,2,3, ... m
\end{equation}

Dimana, 

$D^-_{i}$ adalah jarak alternatif dengan solusi ideal positif

$A^-_{j}$ adalah nilai solusi ideal negatif kriteria ke-$j$

$y_{ij}$ adalah nilai matrix normalisasi terbobot pada alternatif ke-$i$ kriteria ke-$j$

$m$ adalah jumlah alternatif dan $n$ adalah jumlah kriteria

In [54]:
# Kalkulasi Jarak Ideal Positif dan Negatif
# Disini akan menggunakan bantuan fungsi `distance` dari library `scipy.spatial`
# Parameter :
# 1. Matrix normalisasi terbobot
# 2. Nilai solusi ideal positif dan negatif

from scipy.spatial import distance as d

def alt_ideal_distance(w_norm, ideal_v):
    d_positif = []
    d_negatif = []
    
    # Kalkulasi Jarak
    for i in range(w_norm[0].shape[0]):
        # positif
        dp = d.euclidean(w_norm[:,i], ideal_v[:,0])
        d_positif.append(dp)
        
        # negatif
        dn = d.euclidean(ideal_v[:,1], w_norm[:,i])
        d_negatif.append(dn)
    
    d_positif = np.asarray(d_positif)
    d_negatif = np.asarray(d_negatif)
    
    d_value = np.array([d_positif, d_negatif])
        
    return d_value.transpose()

In [58]:
# Testing Jarak Ideal Positif
distance = alt_ideal_distance(w_norm, ideal_v)
print(distance)

[[10.1999592  16.08429213]
 [ 8.86189002 16.85854461]
 [14.5999279  10.11025743]
 [ 5.74339065 16.80442394]]


In [63]:
distance.shape

(4, 2)

### 5. Menghitung Skor Akhir tiap Alternatif

Untuk menghitung skor akhir tiap alternatif, digunakan persamaan,

\begin{equation}
V_i = \frac{D^-_{i}}{D^-_{i}+D^+_{i}}
\end{equation}

Dimana,

$V_i$ adalah skor akhir tiap alternatif

$D^-_{i}$ adalah jarak alternatif dan nilai ideal negatif

$D^+_{i}$ adalah jarak alternatif dan nilai ideal positif

In [66]:
# Kalkulsi skor akhir
# Parameter :
# 1. distance : matrix jarak solusi positif dan negatif. 
# Baris adalah kriteria, kolom adalah solusi ideal positif dan negatif

def final_rank(distance):
    v = []
    
    for i in range(distance.shape[0]):
        vi = distance[i][1] / (distance[i][1] + distance[i][0])
        v.append(vi)
    
    return np.asarray(v)

In [69]:
# Testing skor akhir
ranking = final_rank(distance)
print(ranking)

[0.61193648 0.65545333 0.40915344 0.7452795 ]


---
## Full Code
---

In [72]:
# Data Pengujian 
import numpy as np


# Membuat array 2d sesuai dengan matrix penyekalaan
init_matrix = np.array([[3,3,4,3], [4,2,4,4], [2,4,3,3], [1,1,4,1]])

# Bobot untuk Kriteria C1, C2, C3, dan C4
c_weights = np.array([20,30,30,20])

# Membuat label benefit dan cost untuk tiap kriteria
# Benefit = 1
# Cost = 0
c_label = np.array([1, 1, 1, 0])

In [73]:
# Fungsi TOPSIS Step by Step

import numpy as np
import math
from scipy.spatial import distance as d

def normalization(matrix):
    """
    Normalisasi matrix
    
    Params:
    matrix - matrix hasil dari penyekalaan dalam bentuk 2d array / list
    
    Returns:
    2d array matrix ternormalisasi
    """
    row_values = []
    norm_matrix = []
    
    for i in range(matrix.shape[0]): # Looping per baris (kriteria)
        # Menghitung sum tiap x_{ij}^2
        sum_row = sum([pow(x,2) for x in matrix[i]])
        
        for j in range(matrix[i].shape[0]): # Looping per kolom (alternatif)
            # membangi nilai asli x_{ij} dengan hasil akar
            r_value = matrix[i][j] / math.sqrt(sum_row)
            
            # Masukkan hasil normalisasi ke list tiap baris
            row_values.append(r_value)
        
        #Masukkan hasil normalisasi per baris ke matrix normalisasi
        norm_matrix.append(row_values)
        
        #Kosongkan list normalisasi perbaris
        row_values = []
            
    # Return matrix normalisasi dalam bentuk numpy array
    return np.asarray(norm_matrix)


def weighted_normalization(n_matrix, c_weights):
    """
    Kalkulasi matrix normalisasi terbobot
    
    Params:
    n_matrix - matrix yang sudah dinormalisasi dalam bentuk 2d array / list
    c_weights - bobot tiap kriteria dalam bentuk array / 
    
    Returns:
    2d array matrix normalisasi terbobot
    """
    
    # Buat salinan nilai ternormalisasi
    norm_weighted = n_matrix
    
    for i in range(c_weights.shape[0]): # Looping tiap kriteria
        # Kalkulasi normalisasi terbobot
        norm_weighted[i] = [r * c_weights[i] for r in norm_weighted[i]]
    
    return np.asarray(norm_weighted)


def ideal(w_norm, c_label):
    """
    Menentukan Solusi Ideal Positif dan Negatif
    
    Params:
    w_norm - matrix normalisasi terbobot dalam bentuk 2d array
    c_label - label benefit / cost untuk setiap kriteria dalam bentuk array / list
    
    Returns:
    ideal_value - ideal value untuk solusi ideal positif dan negatif dalam bentuk 2d array
    """
    a_positif = []
    a_negatif = []
    
    for i in range(w_norm.shape[0]):
        if c_label[i] == 1:
            # Untuk ideal positif
            a_max = max(w_norm[i])
            a_positif.append(a_max)
            
            # Untuk ideal negatif
            a_min = min(w_norm[i])
            a_negatif.append(a_min)
        elif c_label[i] == 0:
            # Untuk ideal positif
            a_max = min(w_norm[i])
            a_positif.append(a_max)
            
            # Untuk ideal negatif
            a_min = max(w_norm[i])
            a_negatif.append(a_min)
    
    ideal_value = np.array([a_positif, a_negatif])
    
    # Return dalam bentuk transpose sehingga baris = kriteria, kolom = solusi ideal positif dan negatid
    return ideal_value.transpose()


def alt_ideal_distance(w_norm, ideal_v):
    """
    Menghitung jarak alternatif dengan solusi ideal positif dan negatif
    
    Params:
    w_norm - 2d array matrix normalisasi terbobot
    ideal_v - 2d array matrix solusi ideal positif dan negatif
    
    Returns:
    d_value - jarak alternatif dengan solusi ideal positif dan negatif. 2d array
    """
    d_positif = []
    d_negatif = []
    
    # Kalkulasi Jarak
    for i in range(w_norm[0].shape[0]):
        # positif
        dp = d.euclidean(w_norm[:,i], ideal_v[:,0])
        d_positif.append(dp)
        
        # negatif
        dn = d.euclidean(ideal_v[:,1], w_norm[:,i])
        d_negatif.append(dn)
    
    d_positif = np.asarray(d_positif)
    d_negatif = np.asarray(d_negatif)
    
    d_value = np.array([d_positif, d_negatif])
        
    return d_value.transpose()


def final_rank(distance):
    """
    Kalkulasi skor akhir tiap alternatif
    
    Params:
    distance - jarak alt dengan solusi ideal posifit dan negatif. 2d array
    
    Returns:
    Skor akhir dalam bentuk 2d array
    """
    v = []
    
    for i in range(distance.shape[0]):
        vi = distance[i][1] / (distance[i][1] + distance[i][0])
        v.append(vi)
    
    return np.asarray(v)