In [1]:
import numpy as np

In [25]:
# Bobot
W = np.array([0.2, 0.25, 0.15, 0.4])

# Nilai kriteria
A = np.array([[15, 20, 15, 50], [20, 25, 25, 30], [25, 15, 30, 30], [10, 30, 40, 20]])
# A = np.transpose(A)
#A = np.array([[2,4,3], [7000000, 10000000, 8500000], [2012, 2015, 2010], [7, 2, 4], [3, 3, 4]])
L = np.array(['benefit', 'cost', 'cost', 'benefit'])
#W = np.array([0.3, 0.2, 0.2, 0.2, 0.1])
print(A)

[[15 20 15 50]
 [20 25 25 30]
 [25 15 30 30]
 [10 30 40 20]]


In [26]:
def calculate_wpm(values, weight, label):
    if not values.shape[0] == label.shape[0]:
        print('Jumlah kriteria dan label tidak match!')
        return
    elif not values.shape[0] == weight.shape[0]:
        print('Jumalah kriteria dan bobot tidak match!')
        return
    
    alt_crit_value = []
    all_value = []
    all_wpm = []
    
    values = np.transpose(values)
    
    for i in range(values.shape[0]): # Loop through alternatives
        for j in range(values[i].shape[0]): # Loop through criterias
            if label[j] == 'benefit':
                val = pow(values[i][j], weight[j])
                alt_crit_value.append(val)
            elif label[j] == 'cost':
                val = pow(values[i][j], -weight[j])
                alt_crit_value.append(val)
                
        all_value.append(alt_crit_value)
        alt_crit_value = []
        
        wpm = np.prod(all_value)
        all_wpm.append(wpm)
        all_value = []
    
    # Calculate final preferension
    final = []
    
    for i in range(len(all_wpm)):
        f = all_wpm[i] / np.sum(all_wpm)
        final.append(f)
    
    
    return final

In [27]:
np.set_printoptions(suppress=True, precision=10)
a = calculate_wpm(A, W, L)
print(a)

[0.17371431862686815, 0.2915557934360771, 0.27832673408710423, 0.25640315384995044]
